### PR TITLE
Remove the APIs deleted from SDK in apiref.nsf.

### PR DESCRIPTION
**Pull request by shaiknayabrasool-s**

### CODE REVIEW

**Review by Daniel-Nashed — COMMENTED** [review]
why are those API calls removed from the reference guide?

beside DTableReplaceExt() which is exposed as DTableReplaceExtended() all other calls exist.

**Comment by raghu-madat** [comment]
> why are those API calls removed from the reference guide?
> 
> beside DTableReplaceExt() which is exposed as DTableReplaceExtended() all other calls exist.

@Daniel-Nashed  Those APIs are not exposed now. So we are deleting them from the API ref guide.

**Comment by Daniel-Nashed** [comment]
> > why are those API calls removed from the reference guide?
> > beside DTableReplaceExt() which is exposed as DTableReplaceExtended() all other calls exist.
> 
> @Daniel-Nashed Those APIs are not exposed now. So we are deleting them from the API ref guide.

@raghu-madat  that's not really an answer to my question. why are they not exposed any more? 
This is not how the C-API works! Once it has been exposed, a function should never be removed from the SDK.
Customers might use those functions and could not compile their applications if the calls are missing in a newer API version.
Unless there is a valid reason (e.g. a security concern) no functionality exposed in an earlier the SDK should be removed in a later SDK.

**Comment by shaiknayabrasool-s** [comment]
Creating new one. closed now.

**Pull request closed without merging**
